name: Cypress Tests
 
on:
  push:
    branches:
      - main
 
 
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          config-file: cypress.config.js
          build: npm run build
          start: npm start
          browser: edge
          record: true
